markdown:     kramdown
highlighter:  rouge

title:        JustDesign Cooperative, LLC
tagline:      'The Social Justice Design Cooperative'
baseurl:      ''
paginate:     999
permalink:    :title

plugins:
  - jekyll-paginate
  - github-pages

sass:
    load_paths:
        - _sass

exclude: []
