markdown:     kramdown
highlighter:  rouge

title:        danwahl.github.io
tagline:      'making things (better)'
baseurl:      ''
paginate:     999
permalink:    :title

plugins:
  - jekyll-paginate
  - github-pages

sass:
    load_paths:
        - _sass

exclude: []
