markdown:            kramdown
highlighter:         rouge

title:               JustDesign Cooperative, LLC
tagline:             'Creativity for the Common Good'
baseurl:             ''
paginate:            5
paginate_path:       /page:num/
permalink:           /blog/:title

google_analytics:    UA-96195887-1

plugins:
  - jekyll-paginate
  - github-pages
  - jekyll-redirect-from

sass:
    load_paths:
        - _sass

include:
  - _pages
  - _posts
  - _projects
exclude:             []

collections:
  projects:
    output:          true
    permalink:       /:collection/:title
