# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
locale                   : "en"
title                    : "JustDesign Cooperative, LLC"
title_separator          : "-"
name                     : "JustDesign"
description              : "The Social Justice Design Cooperative"
url                      : "http://justdesigncoop.org"
baseurl                  : ""
repository               : "justdesigncoop"
teaser                   : "/assets/images/logo.png"
minimal_mistakes_skin    : "justdesign"

address                  : "1839 S Troy St, Chicago, IL 60623"
phone                    : "(773) 789-8453"

# breadcrumbs            : false # true, false (default)
atom_feed:
  path                   : # blank (default) uses feed.xml

# Social Sharing
twitter:
  username               : "justdesigncoop"
facebook:
  username               : "justdesigncoop"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-96195887-1"


# Site Author
author:
  name             : "JustDesign"
  avatar           : "/assets/images/logo-small.png"
  bio              : "The Social Justice Design Cooperative"
  location         : "Chicago, IL"
  email            : "justdesigncoop@gmail.com"
  uri              : "http://justdesigncoop.org"
  facebook         : "justdesigncoop"
  github           : "justdesigncoop"
  instagram        : "justdesigncoop"
  twitter          : "justdesigncoop"


# Reading Files
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: :title
paginate: 999 # amount of posts to show
paginate_path: /page:num/
timezone: "US/Central"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
    
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false

# prose.io
prose:
#  rooturl: '_posts'
  siteurl: 'http://justdesigncoop.github.io/'
#  relativeLinks: 'http://justdesigncoop.github.io/links.jsonp'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "single"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          value: ""
    _projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "single"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          value: ""
