---
published: false
---
## The Longest Shutdown in U.S. History


![](https://infogram.com/1pr955gz3ryl20hg2ekyr5vmr3tm9zqn36v)

The third Government Shutdown of President Trump's administration began on December 22nd and is now the longest in U.S. history. Despite what some have said, we are paying through the nose for this shutdown. Due to lost productivity, the inefficiency of closing and reopening, and the lost profitability of adjacent businesses, like towns and attractions near national parks, or service workers government employees [usually rely on but can no longer pay](https://www.vox.com/first-person/2019/1/9/18175506/government-shutdown-furlough-child-care-restaurant-taxi-drivers). Every week of a _full_ government shutdown costs the U.S. [an estimated $6.5 billion dollars](http://fortune.com/2019/01/09/govt-shutdown-2019-costs-billions/). While the current shutdown is partial, not full, it impacts about a quarter of the federal government, or 800,000 employees. The impact is vast and growing.

# "The Essence of Involuntary Servitude"

First, there are the employees required to continue to work without pay. This includes TSA, air traffic control, Federal Bureau of Prisons (including correctional employees), secret service, Drug Enforcement Administration, Coast Guard, Border Patrol, as well as many federal immigration judges and attorneys. Ironically, this [slows immigration court proceedings](https://www.nytimes.com/2019/01/02/us/whats-affected-government-shutdown.html), which the president’s administration previously [worked to expedite](https://www.hrw.org/news/2018/08/16/qa-trump-administrations-zero-tolerance-immigration-policy). Despite the patent injustice of working without pay, federal employees are barred from striking by the [Taft-Hartley Act](https://www.theatlantic.com/politics/archive/2019/01/shutdown-federal-workers-cant-strike/579793/), enacted in 1947. A judge reinforced this perception, ruling that the government [was not obliged to pay federal employees](https://www.washingtonpost.com/nation/2019/01/15/essence-involuntary-servitude-federal-unions-sue-trump-administration-get-paid-shutdown-work/?utm_term=.2de393c8447e) working without pay during the shutdown, despite their claim that the current scenario is “the essence of involuntary servitude,” slavery in as many words. During a brief shutdown this was acceptable, but as Trump and his administration threatens to extend the shutdown for [months or even years](https://www.theatlantic.com/politics/archive/2019/01/trump-shutdown-could-last-months-or-even-years/579535/). A recent op ed penned by a senior white house official ran in The Call , a conservative news site, expressing hope that a prolonged shutdown [will force resignations of employees](https://thehill.com/homenews/administration/425377-Trump-shares-article-blasting-federal-workers-calling-for-long-shutdown). This disdain is chilling. What employee can afford to remain on the job indefinitely without income? When employees are forced to quit in order to pay their bills, how will the government continue to operate when it cannot hire additional staff? 

# Furlough

Second are the employees that are ordered to stay home without pay. Agencies closed for the shutdown include the National Parks (where at least three people have died since the shutdown began), museums, and zoos, as well as important regulatory agencies such as the [DOT](https://www.transportation.gov/mission/unemployment-compensation-during-government-shutdown-furlough), [EPA](https://www.epa.gov/aboutepa/us-epa-contingency-plan-event-government-shutdown), [FDA](https://www.fda.gov/), [IRS](https://thehill.com/business-a-lobbying/424646-shutdown-chaos-complicates-irs-tax-season), [HUD](https://www.hud.gov/), and [SEC](https://www.sec.gov/), as well as science and research entities, including the [Fish and Wildlife Service](https://www.fws.gov/), and [NOAA](https://www.noaa.gov/). That means industry and food aren’t being inspected, tax preparations are [proceeding](https://www.irs.gov/newsroom/irs-confirms-tax-filing-season-to-begin-january-28) (despite a furlough and yet-to-be-finalized tax form for the new tax code), and IPO delays and even investment fraud are more likely. Of all the agencies, only HUD highlights resources for [employees experiencing financial hardship](http://www.foh4you.com/) and resigning during the shutdown. Bills are not on furlough after all, though some cell phone providers and [electrical cooperatives](https://www.eacourier.com/news/government-shutdown-safford-to-propose-utility-shutoff-reprieve-for-federal/article_154f3272-151f-11e9-a401-e72da25a3fc1.html) have created payment plans and other programs intending to lighten the burden on furloughed employees, but as the shutdown continues that may not be enough.

![expirings8.png]({{site.baseurl}}/_posts/expirings8.png)
[explore the above interactive map here](https://nlihc.org/issues/budget/shutdown-map)

# Expiring Funding and Missed Opportunities

The story does not end there, however, as suspended funding impacts many of our most vulnerable neighbors, as well as our future:
-Because it is shut, the federal government is [not able to authorize payment of a $5 million water bill](https://abcnews.go.com/beta-story-container/Politics/shutdown-stops-federal-government-paying-million-water-bill/story?id=60260452) to the District of Columbia. While the water utility does not anticipate budget shortfalls or other problems in the near-term, it could begin shutting off water after 30 days of non-payment.
-[No food aid or non-emergency medical funds](https://www.nytimes.com/2019/01/01/us/native-american-government-shutdown.html?module=inline) will be paid to native american reservations, though states may continue to pay out whatever remains from the last appropriations bill. Food stamps for the rest of the country will [vary state by state](https://www.businessinsider.com/government-shutdown-are-food-stamps-snap-wic-benefits-paid-2019-1), depending on state reserves as no additional money will enter the system until the shutdown ends.
-The Violence Against Women Act expired, [ending funding for survivors of domestic violence, stalking and sexual assault](https://www.thehotline.org/resources/vawa/). While many sources of funding may exist, programs that relied on federal reimbursement for support may be forced to limit services or close altogether. 
-[Loans promised to farmers hurting from tariffs will not be issued](https://www.pbs.org/newshour/politics/the-many-ways-the-shutdown-is-stopping-vital-services-and-research). This fall record quantities of corn and extremely perishable soybean crops were stored at home, wherever and however farmers could find storage, instead of shipped abroad to Asian markets. Farmers hoped that the spring would bring better prices; if they are not able to get loans or find sellers for last year's crop the coming growing season will be a hard one. USDA will  not be processing loans, an essential part of agriculture, to underwrite the costs of purchasing seeds, building infrastructure, and other improvements necessary for a productive growing season.
-[E-verify services are offline](https://www.pbs.org/newshour/politics/the-many-ways-the-shutdown-is-stopping-vital-services-and-research), keeping businesses from registering in the program, using its services, and of course slowing the hiring process for employees.
-B[eer and tobacco labelling procedures are closed](https://www.pbs.org/newshour/politics/the-many-ways-the-shutdown-is-stopping-vital-services-and-research), so any new products will be delayed getting to market, potentially impacting revenues and thus hiring and labor practices.
-[FDA testing is at a standstill](https://www.pbs.org/newshour/politics/the-many-ways-the-shutdown-is-stopping-vital-services-and-research), and no approvals of new drugs and medical devices will be issued until the shutdown ends. Generic drugs, opioid treatment and immunotherapy, along with similar life-saving treatments and procedures will be delayed in reaching those in need.
-Infrastructure is mostly a long-term game, however the EPA’s closure does impact some water treatment projects. Highway funding continues, supported by user fees and gas taxes, untouched by the current shutdown. [Transit, bikes, and pedestrians, however, do not enjoy such funds](https://www.enr.com/articles/46127-shutdown-affects-some-but-not-all-infrastructure-programs). Better Utilizing Investments to Leveraging Development (BUILD, formerly TIGER) funding, used for multimodal (pedestrian, transit, and bicycle infrastructure, transit oriented development, and accessibility improvements), is halted. The Federal Transit Authority’s furlough similarly stops reimbursements and approval of funds for new and existing transit projects. While state and local programs can continue to spend their existing funds, they cannot seek additional funds, or secure funding for continuing programming. [Amtrak will continue without interruption](https://www.railwayage.com/freight/what-the-government-shutdown-means-for-rail/) until it runs out of money, as it is publicly owned and subsidized, but run as an enterprise.
-[1,150 Section 8 contracts have not been renewed](https://nlihc.org/sites/default/files/FY19_Shutdown_Factsheet.pdf), impacting approximately 80,000 households, of which 2/3s are estimated to be elderly or disabled and thus unlikely to have alternatives to Section 8 rental support. 500 additional contracts will come due over the course of January, and 550 additional contract are due in February. This means the number of households at risk of eviction will double in the next two months. And a temporary continuing resolution, while helpful for employees, will not alleviate this problem, since at least 12 months of funding is necessary to renew contracts that support leases, as well as ongoing maintenance and repairs. [The impact will be felt across the U.S.](https://nlihc.org/article/update-shutdown-s-impact-housing-and-how-take-action)
-3,000 Public Housing Authorities (PHAs) are established in most major U.S. cities to develop and operate [local project-based public housing](https://nlihc.org/issues/budget/shutdown-map). There is a 60-day lag on funding for PHAs following federal appropriation, so while there is no immediate shortfall of funding, there may be a lengthy period following the shutdown during which operations and maintenance will be underfunded. [There is a chronic $26 billion capital backlog in needed upgrades and maintenance, which will only continue to grow](https://nlihc.org/sites/default/files/FY19_Shutdown_Factsheet.pdf). Even if the funds exist, PHAs must seek approval from HUD to implement the funds, and with HUD out on furlough, this is currently impossible. 
-PHAs also operate Housing Choice Voucher (HCV) programs, similar to Section 8 in theory, but operated specifically to reduce the concentration (and segregation) of low income families. The funding for this will be delayed along with other PHA funding, meaning that the risk for eviction for families in this program will show up on March 1st. Neither will PHAs be able to process waitlist families hoping for a voucher. Both will have to find the money to pay market rate rent, whether they are used to it or not.
-Construction of new affordable, subsidized, and public housing, as well as renovations of existing facilities, is halted, costing non-profits, developers, contractors, and construction workers.
-Grants and funding from HUD drives a wide array of programming. Applications will not be reviewed, requests for reimbursement will not be reviewed, nor will funding opportunities be updated on websites until the shutdown ends. This means that essential homeless services in the dead of winter may close their doors, unless private funding makes up for lost federal support. Community Development Block Grants (CDBG) promote new construction as well as human capital development, will not be paid. Some CDBGs specifically focused on disaster recovery have not been paid for years, causing Texas officials to send a letter stating that [they can wait no longer for these funds](https://nlihc.org/issues/budget/shutdown-map), promised when Hurricane Harvey struck in 2017.

JustDesign was formed to supplement and complement often-insufficient public services, providing [air quality monitoring](http://airqualitychicago.org/), [public health education](https://pilsenperro.org/uic-includes-testing-data-results-in-pilsen/), and [community engagement](https://www.webuildagency.org/work/2018/10/epa-community-involvement-training). In this government shutdown, we feel our mandate more clearly than ever before. How are you doing with the government closed? Where would you like to see us serving in the new year?
